/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PageRouteImport } from './routes/$page'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as BillingRouteRouteImport } from './routes/billing/route'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/auth/route'
import { Route as AutheddashboardRouteRouteImport } from './routes/_authed/(dashboard)/route'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ForumsIndexRouteImport } from './routes/forums/index'
import { Route as ForumsThreadIdRouteImport } from './routes/forums/$threadId'
import { Route as NovelSlugRouteImport } from './routes/novel/$slug'
import { Route as NovelsIndexRouteImport } from './routes/novels/index'
import { Route as NovelsSlugRouteImport } from './routes/novels/$slug'
import { Route as TagsSlugRouteImport } from './routes/tags/$slug'
import { Route as WorldsIndexRouteImport } from './routes/worlds/index'
import { Route as authAuthUnauthedRouteRouteImport } from './routes/(auth)/auth/_unauthed/route'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/auth/reset-password'
import { Route as AutheddashboardAdminRouteImport } from './routes/_authed/(dashboard)/admin'
import { Route as AutheddashboardDashboardRouteRouteImport } from './routes/_authed/(dashboard)/dashboard/route'
import { Route as AutheddashboardHelpRouteImport } from './routes/_authed/(dashboard)/help'
import { Route as AutheddashboardPurchasesRouteImport } from './routes/_authed/(dashboard)/purchases'
import { Route as PubliclegalPrivacyRouteImport } from './routes/_public/(legal)/privacy'
import { Route as PubliclegalTermsRouteImport } from './routes/_public/(legal)/terms'
import { Route as PublicmarketingContactRouteImport } from './routes/_public/(marketing)/contact'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as LibraryGenreSlugRouteImport } from './routes/library/genre/$slug'
import { Route as NovelsCategoriesSlugRouteImport } from './routes/novels/categories/$slug'
import { Route as NovelsGenreSlugRouteImport } from './routes/novels/genre/$slug'
import { Route as TagsNovelsSlugRouteImport } from './routes/tags/novels/$slug'
import { Route as authAuthUnauthedForgotPasswordRouteImport } from './routes/(auth)/auth/_unauthed/forgot-password'
import { Route as authAuthUnauthedSignInRouteImport } from './routes/(auth)/auth/_unauthed/sign-in'
import { Route as authAuthUnauthedSignUpRouteImport } from './routes/(auth)/auth/_unauthed/sign-up'
import { Route as AutheddashboardAdminIndexRouteImport } from './routes/_authed/(dashboard)/admin/index'
import { Route as AutheddashboardAdminAnalyticsRouteImport } from './routes/_authed/(dashboard)/admin/analytics'
import { Route as AutheddashboardAdminAuditRouteImport } from './routes/_authed/(dashboard)/admin/audit'
import { Route as AutheddashboardAdminIntegrationsRouteImport } from './routes/_authed/(dashboard)/admin/integrations'
import { Route as AutheddashboardAdminPaymentsRouteImport } from './routes/_authed/(dashboard)/admin/payments'
import { Route as AutheddashboardAdminSystemRouteImport } from './routes/_authed/(dashboard)/admin/system'
import { Route as AutheddashboardAdminUsersRouteImport } from './routes/_authed/(dashboard)/admin/users'
import { Route as AutheddashboardCreditsPurchaseRouteImport } from './routes/_authed/(dashboard)/credits/purchase'
import { Route as AutheddashboardCreditsTransactionsRouteImport } from './routes/_authed/(dashboard)/credits/transactions'
import { Route as AutheddashboardSettingsIndexRouteImport } from './routes/_authed/(dashboard)/settings/index'
import { Route as AutheddashboardSettingsBillingRouteImport } from './routes/_authed/(dashboard)/settings/billing'
import { Route as AutheddashboardSettingsProfileRouteImport } from './routes/_authed/(dashboard)/settings/profile'
import { Route as AutheddashboardSettingsSecurityRouteImport } from './routes/_authed/(dashboard)/settings/security'
import { Route as AutheddashboardTicketsIndexRouteImport } from './routes/_authed/(dashboard)/tickets/index'
import { Route as AutheddashboardTicketsTicketIdRouteImport } from './routes/_authed/(dashboard)/tickets/$ticketId'
import { Route as PublicmarketinglandingPageIndexRouteImport } from './routes/_public/(marketing)/(landing-page)/index'
import { Route as PublicmarketingBlogIndexRouteImport } from './routes/_public/(marketing)/blog/index'
import { Route as PublicmarketingBlogSlugRouteImport } from './routes/_public/(marketing)/blog/$slug'
import { Route as PublicmarketingDesignSystemIndexRouteImport } from './routes/_public/(marketing)/design-system/index'
import { Route as NovelSlugChapterNumberRouteImport } from './routes/novel/$slug/chapter/$number'
import { Route as NovelsSlugChapterNumberRouteImport } from './routes/novels/$slug/chapter/$number'
import { Route as AutheddashboardAdminSupportIndexRouteImport } from './routes/_authed/(dashboard)/admin/support/index'
import { Route as AutheddashboardAdminSupportTicketIdRouteImport } from './routes/_authed/(dashboard)/admin/support/$ticketId'
import { Route as PublicmarketingBlogCategorySlugRouteImport } from './routes/_public/(marketing)/blog/category/$slug'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRouteRoute = BillingRouteRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutheddashboardRouteRoute = AutheddashboardRouteRouteImport.update({
  id: '/_authed/(dashboard)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => BillingRouteRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRouteRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/$.lazy').then((d) => d.Route))
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsThreadIdRoute = ForumsThreadIdRouteImport.update({
  id: '/forums/$threadId',
  path: '/forums/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelSlugRoute = NovelSlugRouteImport.update({
  id: '/novel/$slug',
  path: '/novel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsIndexRoute = NovelsIndexRouteImport.update({
  id: '/novels/',
  path: '/novels/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsSlugRoute = NovelsSlugRouteImport.update({
  id: '/novels/$slug',
  path: '/novels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/worlds/',
  path: '/worlds/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthUnauthedRouteRoute = authAuthUnauthedRouteRouteImport.update({
  id: '/_unauthed',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const AutheddashboardAdminRoute = AutheddashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AutheddashboardRouteRoute,
} as any)
const AutheddashboardDashboardRouteRoute =
  AutheddashboardDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardHelpRoute = AutheddashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AutheddashboardRouteRoute,
} as any)
const AutheddashboardPurchasesRoute =
  AutheddashboardPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const PubliclegalPrivacyRoute = PubliclegalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PubliclegalTermsRoute = PubliclegalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicmarketingContactRoute = PublicmarketingContactRouteImport.update({
  id: '/(marketing)/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryGenreSlugRoute = LibraryGenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => LibraryRoute,
} as any)
const NovelsCategoriesSlugRoute = NovelsCategoriesSlugRouteImport.update({
  id: '/novels/categories/$slug',
  path: '/novels/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsGenreSlugRoute = NovelsGenreSlugRouteImport.update({
  id: '/novels/genre/$slug',
  path: '/novels/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsNovelsSlugRoute = TagsNovelsSlugRouteImport.update({
  id: '/tags/novels/$slug',
  path: '/tags/novels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthUnauthedForgotPasswordRoute =
  authAuthUnauthedForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authAuthUnauthedRouteRoute,
  } as any)
const authAuthUnauthedSignInRoute = authAuthUnauthedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthUnauthedRouteRoute,
} as any)
const authAuthUnauthedSignUpRoute = authAuthUnauthedSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthUnauthedRouteRoute,
} as any)
const AutheddashboardAdminIndexRoute =
  AutheddashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminAnalyticsRoute =
  AutheddashboardAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminAuditRoute =
  AutheddashboardAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminIntegrationsRoute =
  AutheddashboardAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminPaymentsRoute =
  AutheddashboardAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminSystemRoute =
  AutheddashboardAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminUsersRoute =
  AutheddashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardCreditsPurchaseRoute =
  AutheddashboardCreditsPurchaseRouteImport.update({
    id: '/credits/purchase',
    path: '/credits/purchase',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardCreditsTransactionsRoute =
  AutheddashboardCreditsTransactionsRouteImport.update({
    id: '/credits/transactions',
    path: '/credits/transactions',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardSettingsIndexRoute =
  AutheddashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardSettingsBillingRoute =
  AutheddashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardSettingsProfileRoute =
  AutheddashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardSettingsSecurityRoute =
  AutheddashboardSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardTicketsIndexRoute =
  AutheddashboardTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardTicketsTicketIdRoute =
  AutheddashboardTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const PublicmarketinglandingPageIndexRoute =
  PublicmarketinglandingPageIndexRouteImport.update({
    id: '/(marketing)/(landing-page)/',
    path: '/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicmarketingBlogIndexRoute =
  PublicmarketingBlogIndexRouteImport.update({
    id: '/(marketing)/blog/',
    path: '/blog/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicmarketingBlogSlugRoute = PublicmarketingBlogSlugRouteImport.update({
  id: '/(marketing)/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicmarketingDesignSystemIndexRoute =
  PublicmarketingDesignSystemIndexRouteImport.update({
    id: '/(marketing)/design-system/',
    path: '/design-system/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const NovelSlugChapterNumberRoute = NovelSlugChapterNumberRouteImport.update({
  id: '/chapter/$number',
  path: '/chapter/$number',
  getParentRoute: () => NovelSlugRoute,
} as any)
const NovelsSlugChapterNumberRoute = NovelsSlugChapterNumberRouteImport.update({
  id: '/chapter/$number',
  path: '/chapter/$number',
  getParentRoute: () => NovelsSlugRoute,
} as any)
const AutheddashboardAdminSupportIndexRoute =
  AutheddashboardAdminSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const AutheddashboardAdminSupportTicketIdRoute =
  AutheddashboardAdminSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => AutheddashboardAdminRoute,
  } as any)
const PublicmarketingBlogCategorySlugRoute =
  PublicmarketingBlogCategorySlugRouteImport.update({
    id: '/(marketing)/blog/category/$slug',
    path: '/blog/category/$slug',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicmarketinglandingPageIndexRoute
  '/billing': typeof BillingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$page': typeof PageRoute
  '/announcements': typeof AnnouncementsRoute
  '/library': typeof LibraryRouteWithChildren
  '/ranking': typeof RankingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth': typeof authAuthRouteRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/search': typeof ApiSearchRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/forums/$threadId': typeof ForumsThreadIdRoute
  '/novel/$slug': typeof NovelSlugRouteWithChildren
  '/novels/$slug': typeof NovelsSlugRouteWithChildren
  '/tags/$slug': typeof TagsSlugRoute
  '/forums/': typeof ForumsIndexRoute
  '/novels/': typeof NovelsIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/dashboard': typeof AutheddashboardDashboardRouteRoute
  '/auth/reset-password': typeof authAuthResetPasswordRoute
  '/admin': typeof AutheddashboardAdminRouteWithChildren
  '/help': typeof AutheddashboardHelpRoute
  '/purchases': typeof AutheddashboardPurchasesRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/terms': typeof PubliclegalTermsRoute
  '/contact': typeof PublicmarketingContactRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/library/genre/$slug': typeof LibraryGenreSlugRoute
  '/novels/categories/$slug': typeof NovelsCategoriesSlugRoute
  '/novels/genre/$slug': typeof NovelsGenreSlugRoute
  '/tags/novels/$slug': typeof TagsNovelsSlugRoute
  '/auth/forgot-password': typeof authAuthUnauthedForgotPasswordRoute
  '/auth/sign-in': typeof authAuthUnauthedSignInRoute
  '/auth/sign-up': typeof authAuthUnauthedSignUpRoute
  '/admin/analytics': typeof AutheddashboardAdminAnalyticsRoute
  '/admin/audit': typeof AutheddashboardAdminAuditRoute
  '/admin/integrations': typeof AutheddashboardAdminIntegrationsRoute
  '/admin/payments': typeof AutheddashboardAdminPaymentsRoute
  '/admin/system': typeof AutheddashboardAdminSystemRoute
  '/admin/users': typeof AutheddashboardAdminUsersRoute
  '/credits/purchase': typeof AutheddashboardCreditsPurchaseRoute
  '/credits/transactions': typeof AutheddashboardCreditsTransactionsRoute
  '/settings/billing': typeof AutheddashboardSettingsBillingRoute
  '/settings/profile': typeof AutheddashboardSettingsProfileRoute
  '/settings/security': typeof AutheddashboardSettingsSecurityRoute
  '/tickets/$ticketId': typeof AutheddashboardTicketsTicketIdRoute
  '/blog/$slug': typeof PublicmarketingBlogSlugRoute
  '/novel/$slug/chapter/$number': typeof NovelSlugChapterNumberRoute
  '/novels/$slug/chapter/$number': typeof NovelsSlugChapterNumberRoute
  '/admin/': typeof AutheddashboardAdminIndexRoute
  '/settings/': typeof AutheddashboardSettingsIndexRoute
  '/tickets/': typeof AutheddashboardTicketsIndexRoute
  '/blog/': typeof PublicmarketingBlogIndexRoute
  '/design-system/': typeof PublicmarketingDesignSystemIndexRoute
  '/admin/support/$ticketId': typeof AutheddashboardAdminSupportTicketIdRoute
  '/blog/category/$slug': typeof PublicmarketingBlogCategorySlugRoute
  '/admin/support/': typeof AutheddashboardAdminSupportIndexRoute
}
export interface FileRoutesByTo {
  '/billing': typeof BillingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$page': typeof PageRoute
  '/announcements': typeof AnnouncementsRoute
  '/library': typeof LibraryRouteWithChildren
  '/ranking': typeof RankingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth': typeof authAuthRouteRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/search': typeof ApiSearchRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/forums/$threadId': typeof ForumsThreadIdRoute
  '/novel/$slug': typeof NovelSlugRouteWithChildren
  '/novels/$slug': typeof NovelsSlugRouteWithChildren
  '/tags/$slug': typeof TagsSlugRoute
  '/forums': typeof ForumsIndexRoute
  '/novels': typeof NovelsIndexRoute
  '/worlds': typeof WorldsIndexRoute
  '/dashboard': typeof AutheddashboardDashboardRouteRoute
  '/auth/reset-password': typeof authAuthResetPasswordRoute
  '/help': typeof AutheddashboardHelpRoute
  '/purchases': typeof AutheddashboardPurchasesRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/terms': typeof PubliclegalTermsRoute
  '/contact': typeof PublicmarketingContactRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/library/genre/$slug': typeof LibraryGenreSlugRoute
  '/novels/categories/$slug': typeof NovelsCategoriesSlugRoute
  '/novels/genre/$slug': typeof NovelsGenreSlugRoute
  '/tags/novels/$slug': typeof TagsNovelsSlugRoute
  '/auth/forgot-password': typeof authAuthUnauthedForgotPasswordRoute
  '/auth/sign-in': typeof authAuthUnauthedSignInRoute
  '/auth/sign-up': typeof authAuthUnauthedSignUpRoute
  '/admin/analytics': typeof AutheddashboardAdminAnalyticsRoute
  '/admin/audit': typeof AutheddashboardAdminAuditRoute
  '/admin/integrations': typeof AutheddashboardAdminIntegrationsRoute
  '/admin/payments': typeof AutheddashboardAdminPaymentsRoute
  '/admin/system': typeof AutheddashboardAdminSystemRoute
  '/admin/users': typeof AutheddashboardAdminUsersRoute
  '/credits/purchase': typeof AutheddashboardCreditsPurchaseRoute
  '/credits/transactions': typeof AutheddashboardCreditsTransactionsRoute
  '/settings/billing': typeof AutheddashboardSettingsBillingRoute
  '/settings/profile': typeof AutheddashboardSettingsProfileRoute
  '/settings/security': typeof AutheddashboardSettingsSecurityRoute
  '/tickets/$ticketId': typeof AutheddashboardTicketsTicketIdRoute
  '/blog/$slug': typeof PublicmarketingBlogSlugRoute
  '/novel/$slug/chapter/$number': typeof NovelSlugChapterNumberRoute
  '/novels/$slug/chapter/$number': typeof NovelsSlugChapterNumberRoute
  '/admin': typeof AutheddashboardAdminIndexRoute
  '/settings': typeof AutheddashboardSettingsIndexRoute
  '/tickets': typeof AutheddashboardTicketsIndexRoute
  '/': typeof PublicmarketinglandingPageIndexRoute
  '/blog': typeof PublicmarketingBlogIndexRoute
  '/design-system': typeof PublicmarketingDesignSystemIndexRoute
  '/admin/support/$ticketId': typeof AutheddashboardAdminSupportTicketIdRoute
  '/blog/category/$slug': typeof PublicmarketingBlogCategorySlugRoute
  '/admin/support': typeof AutheddashboardAdminSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/billing': typeof BillingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$page': typeof PageRoute
  '/announcements': typeof AnnouncementsRoute
  '/library': typeof LibraryRouteWithChildren
  '/ranking': typeof RankingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(auth)/auth': typeof authAuthRouteRouteWithChildren
  '/_authed/(dashboard)': typeof AutheddashboardRouteRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/search': typeof ApiSearchRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/forums/$threadId': typeof ForumsThreadIdRoute
  '/novel/$slug': typeof NovelSlugRouteWithChildren
  '/novels/$slug': typeof NovelsSlugRouteWithChildren
  '/tags/$slug': typeof TagsSlugRoute
  '/forums/': typeof ForumsIndexRoute
  '/novels/': typeof NovelsIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/(auth)/auth/_unauthed': typeof authAuthUnauthedRouteRouteWithChildren
  '/_authed/(dashboard)/dashboard': typeof AutheddashboardDashboardRouteRoute
  '/(auth)/auth/reset-password': typeof authAuthResetPasswordRoute
  '/_authed/(dashboard)/admin': typeof AutheddashboardAdminRouteWithChildren
  '/_authed/(dashboard)/help': typeof AutheddashboardHelpRoute
  '/_authed/(dashboard)/purchases': typeof AutheddashboardPurchasesRoute
  '/_public/(legal)/privacy': typeof PubliclegalPrivacyRoute
  '/_public/(legal)/terms': typeof PubliclegalTermsRoute
  '/_public/(marketing)/contact': typeof PublicmarketingContactRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/library/genre/$slug': typeof LibraryGenreSlugRoute
  '/novels/categories/$slug': typeof NovelsCategoriesSlugRoute
  '/novels/genre/$slug': typeof NovelsGenreSlugRoute
  '/tags/novels/$slug': typeof TagsNovelsSlugRoute
  '/(auth)/auth/_unauthed/forgot-password': typeof authAuthUnauthedForgotPasswordRoute
  '/(auth)/auth/_unauthed/sign-in': typeof authAuthUnauthedSignInRoute
  '/(auth)/auth/_unauthed/sign-up': typeof authAuthUnauthedSignUpRoute
  '/_authed/(dashboard)/admin/analytics': typeof AutheddashboardAdminAnalyticsRoute
  '/_authed/(dashboard)/admin/audit': typeof AutheddashboardAdminAuditRoute
  '/_authed/(dashboard)/admin/integrations': typeof AutheddashboardAdminIntegrationsRoute
  '/_authed/(dashboard)/admin/payments': typeof AutheddashboardAdminPaymentsRoute
  '/_authed/(dashboard)/admin/system': typeof AutheddashboardAdminSystemRoute
  '/_authed/(dashboard)/admin/users': typeof AutheddashboardAdminUsersRoute
  '/_authed/(dashboard)/credits/purchase': typeof AutheddashboardCreditsPurchaseRoute
  '/_authed/(dashboard)/credits/transactions': typeof AutheddashboardCreditsTransactionsRoute
  '/_authed/(dashboard)/settings/billing': typeof AutheddashboardSettingsBillingRoute
  '/_authed/(dashboard)/settings/profile': typeof AutheddashboardSettingsProfileRoute
  '/_authed/(dashboard)/settings/security': typeof AutheddashboardSettingsSecurityRoute
  '/_authed/(dashboard)/tickets/$ticketId': typeof AutheddashboardTicketsTicketIdRoute
  '/_public/(marketing)/blog/$slug': typeof PublicmarketingBlogSlugRoute
  '/novel/$slug/chapter/$number': typeof NovelSlugChapterNumberRoute
  '/novels/$slug/chapter/$number': typeof NovelsSlugChapterNumberRoute
  '/_authed/(dashboard)/admin/': typeof AutheddashboardAdminIndexRoute
  '/_authed/(dashboard)/settings/': typeof AutheddashboardSettingsIndexRoute
  '/_authed/(dashboard)/tickets/': typeof AutheddashboardTicketsIndexRoute
  '/_public/(marketing)/(landing-page)/': typeof PublicmarketinglandingPageIndexRoute
  '/_public/(marketing)/blog/': typeof PublicmarketingBlogIndexRoute
  '/_public/(marketing)/design-system/': typeof PublicmarketingDesignSystemIndexRoute
  '/_authed/(dashboard)/admin/support/$ticketId': typeof AutheddashboardAdminSupportTicketIdRoute
  '/_public/(marketing)/blog/category/$slug': typeof PublicmarketingBlogCategorySlugRoute
  '/_authed/(dashboard)/admin/support/': typeof AutheddashboardAdminSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/$'
    | '/$page'
    | '/announcements'
    | '/library'
    | '/ranking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth'
    | '/api/contact'
    | '/api/search'
    | '/billing/cancel'
    | '/billing/success'
    | '/categories/$slug'
    | '/docs/$'
    | '/forums/$threadId'
    | '/novel/$slug'
    | '/novels/$slug'
    | '/tags/$slug'
    | '/forums/'
    | '/novels/'
    | '/worlds/'
    | '/dashboard'
    | '/auth/reset-password'
    | '/admin'
    | '/help'
    | '/purchases'
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/api/newsletter/subscribe'
    | '/library/genre/$slug'
    | '/novels/categories/$slug'
    | '/novels/genre/$slug'
    | '/tags/novels/$slug'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/payments'
    | '/admin/system'
    | '/admin/users'
    | '/credits/purchase'
    | '/credits/transactions'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/tickets/$ticketId'
    | '/blog/$slug'
    | '/novel/$slug/chapter/$number'
    | '/novels/$slug/chapter/$number'
    | '/admin/'
    | '/settings/'
    | '/tickets/'
    | '/blog/'
    | '/design-system/'
    | '/admin/support/$ticketId'
    | '/blog/category/$slug'
    | '/admin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billing'
    | '/$'
    | '/$page'
    | '/announcements'
    | '/library'
    | '/ranking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth'
    | '/api/contact'
    | '/api/search'
    | '/billing/cancel'
    | '/billing/success'
    | '/categories/$slug'
    | '/docs/$'
    | '/forums/$threadId'
    | '/novel/$slug'
    | '/novels/$slug'
    | '/tags/$slug'
    | '/forums'
    | '/novels'
    | '/worlds'
    | '/dashboard'
    | '/auth/reset-password'
    | '/help'
    | '/purchases'
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/api/newsletter/subscribe'
    | '/library/genre/$slug'
    | '/novels/categories/$slug'
    | '/novels/genre/$slug'
    | '/tags/novels/$slug'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/payments'
    | '/admin/system'
    | '/admin/users'
    | '/credits/purchase'
    | '/credits/transactions'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/tickets/$ticketId'
    | '/blog/$slug'
    | '/novel/$slug/chapter/$number'
    | '/novels/$slug/chapter/$number'
    | '/admin'
    | '/settings'
    | '/tickets'
    | '/'
    | '/blog'
    | '/design-system'
    | '/admin/support/$ticketId'
    | '/blog/category/$slug'
    | '/admin/support'
  id:
    | '__root__'
    | '/_public'
    | '/billing'
    | '/$'
    | '/$page'
    | '/announcements'
    | '/library'
    | '/ranking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(auth)/auth'
    | '/_authed/(dashboard)'
    | '/api/contact'
    | '/api/search'
    | '/billing/cancel'
    | '/billing/success'
    | '/categories/$slug'
    | '/docs/$'
    | '/forums/$threadId'
    | '/novel/$slug'
    | '/novels/$slug'
    | '/tags/$slug'
    | '/forums/'
    | '/novels/'
    | '/worlds/'
    | '/(auth)/auth/_unauthed'
    | '/_authed/(dashboard)/dashboard'
    | '/(auth)/auth/reset-password'
    | '/_authed/(dashboard)/admin'
    | '/_authed/(dashboard)/help'
    | '/_authed/(dashboard)/purchases'
    | '/_public/(legal)/privacy'
    | '/_public/(legal)/terms'
    | '/_public/(marketing)/contact'
    | '/api/newsletter/subscribe'
    | '/library/genre/$slug'
    | '/novels/categories/$slug'
    | '/novels/genre/$slug'
    | '/tags/novels/$slug'
    | '/(auth)/auth/_unauthed/forgot-password'
    | '/(auth)/auth/_unauthed/sign-in'
    | '/(auth)/auth/_unauthed/sign-up'
    | '/_authed/(dashboard)/admin/analytics'
    | '/_authed/(dashboard)/admin/audit'
    | '/_authed/(dashboard)/admin/integrations'
    | '/_authed/(dashboard)/admin/payments'
    | '/_authed/(dashboard)/admin/system'
    | '/_authed/(dashboard)/admin/users'
    | '/_authed/(dashboard)/credits/purchase'
    | '/_authed/(dashboard)/credits/transactions'
    | '/_authed/(dashboard)/settings/billing'
    | '/_authed/(dashboard)/settings/profile'
    | '/_authed/(dashboard)/settings/security'
    | '/_authed/(dashboard)/tickets/$ticketId'
    | '/_public/(marketing)/blog/$slug'
    | '/novel/$slug/chapter/$number'
    | '/novels/$slug/chapter/$number'
    | '/_authed/(dashboard)/admin/'
    | '/_authed/(dashboard)/settings/'
    | '/_authed/(dashboard)/tickets/'
    | '/_public/(marketing)/(landing-page)/'
    | '/_public/(marketing)/blog/'
    | '/_public/(marketing)/design-system/'
    | '/_authed/(dashboard)/admin/support/$ticketId'
    | '/_public/(marketing)/blog/category/$slug'
    | '/_authed/(dashboard)/admin/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  BillingRouteRoute: typeof BillingRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  PageRoute: typeof PageRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  RankingRoute: typeof RankingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
  AutheddashboardRouteRoute: typeof AutheddashboardRouteRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ForumsThreadIdRoute: typeof ForumsThreadIdRoute
  NovelSlugRoute: typeof NovelSlugRouteWithChildren
  NovelsSlugRoute: typeof NovelsSlugRouteWithChildren
  TagsSlugRoute: typeof TagsSlugRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  NovelsIndexRoute: typeof NovelsIndexRoute
  WorldsIndexRoute: typeof WorldsIndexRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
  NovelsCategoriesSlugRoute: typeof NovelsCategoriesSlugRoute
  NovelsGenreSlugRoute: typeof NovelsGenreSlugRoute
  TagsNovelsSlugRoute: typeof TagsNovelsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/(dashboard)': {
      id: '/_authed/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AutheddashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof BillingRouteRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof BillingRouteRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/$threadId': {
      id: '/forums/$threadId'
      path: '/forums/$threadId'
      fullPath: '/forums/$threadId'
      preLoaderRoute: typeof ForumsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$slug': {
      id: '/novel/$slug'
      path: '/novel/$slug'
      fullPath: '/novel/$slug'
      preLoaderRoute: typeof NovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/': {
      id: '/novels/'
      path: '/novels'
      fullPath: '/novels/'
      preLoaderRoute: typeof NovelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$slug': {
      id: '/novels/$slug'
      path: '/novels/$slug'
      fullPath: '/novels/$slug'
      preLoaderRoute: typeof NovelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/worlds'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/_unauthed': {
      id: '/(auth)/auth/_unauthed'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthUnauthedRouteRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/auth/reset-password': {
      id: '/(auth)/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/_authed/(dashboard)/admin': {
      id: '/_authed/(dashboard)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AutheddashboardAdminRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/dashboard': {
      id: '/_authed/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AutheddashboardDashboardRouteRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/help': {
      id: '/_authed/(dashboard)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AutheddashboardHelpRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/purchases': {
      id: '/_authed/(dashboard)/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AutheddashboardPurchasesRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_public/(legal)/privacy': {
      id: '/_public/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PubliclegalPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(legal)/terms': {
      id: '/_public/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PubliclegalTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/contact': {
      id: '/_public/(marketing)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicmarketingContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/genre/$slug': {
      id: '/library/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/library/genre/$slug'
      preLoaderRoute: typeof LibraryGenreSlugRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/novels/categories/$slug': {
      id: '/novels/categories/$slug'
      path: '/novels/categories/$slug'
      fullPath: '/novels/categories/$slug'
      preLoaderRoute: typeof NovelsCategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/genre/$slug': {
      id: '/novels/genre/$slug'
      path: '/novels/genre/$slug'
      fullPath: '/novels/genre/$slug'
      preLoaderRoute: typeof NovelsGenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/novels/$slug': {
      id: '/tags/novels/$slug'
      path: '/tags/novels/$slug'
      fullPath: '/tags/novels/$slug'
      preLoaderRoute: typeof TagsNovelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/_unauthed/forgot-password': {
      id: '/(auth)/auth/_unauthed/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authAuthUnauthedForgotPasswordRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/(auth)/auth/_unauthed/sign-in': {
      id: '/(auth)/auth/_unauthed/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof authAuthUnauthedSignInRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/(auth)/auth/_unauthed/sign-up': {
      id: '/(auth)/auth/_unauthed/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof authAuthUnauthedSignUpRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/_authed/(dashboard)/admin/': {
      id: '/_authed/(dashboard)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AutheddashboardAdminIndexRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/analytics': {
      id: '/_authed/(dashboard)/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AutheddashboardAdminAnalyticsRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/audit': {
      id: '/_authed/(dashboard)/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AutheddashboardAdminAuditRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/integrations': {
      id: '/_authed/(dashboard)/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AutheddashboardAdminIntegrationsRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/payments': {
      id: '/_authed/(dashboard)/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AutheddashboardAdminPaymentsRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/system': {
      id: '/_authed/(dashboard)/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AutheddashboardAdminSystemRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/users': {
      id: '/_authed/(dashboard)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AutheddashboardAdminUsersRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/credits/purchase': {
      id: '/_authed/(dashboard)/credits/purchase'
      path: '/credits/purchase'
      fullPath: '/credits/purchase'
      preLoaderRoute: typeof AutheddashboardCreditsPurchaseRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/credits/transactions': {
      id: '/_authed/(dashboard)/credits/transactions'
      path: '/credits/transactions'
      fullPath: '/credits/transactions'
      preLoaderRoute: typeof AutheddashboardCreditsTransactionsRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/settings/': {
      id: '/_authed/(dashboard)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AutheddashboardSettingsIndexRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/settings/billing': {
      id: '/_authed/(dashboard)/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AutheddashboardSettingsBillingRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/settings/profile': {
      id: '/_authed/(dashboard)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AutheddashboardSettingsProfileRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/settings/security': {
      id: '/_authed/(dashboard)/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AutheddashboardSettingsSecurityRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/tickets/': {
      id: '/_authed/(dashboard)/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AutheddashboardTicketsIndexRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/tickets/$ticketId': {
      id: '/_authed/(dashboard)/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AutheddashboardTicketsTicketIdRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_public/(marketing)/(landing-page)/': {
      id: '/_public/(marketing)/(landing-page)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicmarketinglandingPageIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/blog/': {
      id: '/_public/(marketing)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicmarketingBlogIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/blog/$slug': {
      id: '/_public/(marketing)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicmarketingBlogSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/design-system/': {
      id: '/_public/(marketing)/design-system/'
      path: '/design-system'
      fullPath: '/design-system/'
      preLoaderRoute: typeof PublicmarketingDesignSystemIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/novel/$slug/chapter/$number': {
      id: '/novel/$slug/chapter/$number'
      path: '/chapter/$number'
      fullPath: '/novel/$slug/chapter/$number'
      preLoaderRoute: typeof NovelSlugChapterNumberRouteImport
      parentRoute: typeof NovelSlugRoute
    }
    '/novels/$slug/chapter/$number': {
      id: '/novels/$slug/chapter/$number'
      path: '/chapter/$number'
      fullPath: '/novels/$slug/chapter/$number'
      preLoaderRoute: typeof NovelsSlugChapterNumberRouteImport
      parentRoute: typeof NovelsSlugRoute
    }
    '/_authed/(dashboard)/admin/support/': {
      id: '/_authed/(dashboard)/admin/support/'
      path: '/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AutheddashboardAdminSupportIndexRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_authed/(dashboard)/admin/support/$ticketId': {
      id: '/_authed/(dashboard)/admin/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AutheddashboardAdminSupportTicketIdRouteImport
      parentRoute: typeof AutheddashboardAdminRoute
    }
    '/_public/(marketing)/blog/category/$slug': {
      id: '/_public/(marketing)/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof PublicmarketingBlogCategorySlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PubliclegalPrivacyRoute: typeof PubliclegalPrivacyRoute
  PubliclegalTermsRoute: typeof PubliclegalTermsRoute
  PublicmarketingContactRoute: typeof PublicmarketingContactRoute
  PublicmarketingBlogSlugRoute: typeof PublicmarketingBlogSlugRoute
  PublicmarketinglandingPageIndexRoute: typeof PublicmarketinglandingPageIndexRoute
  PublicmarketingBlogIndexRoute: typeof PublicmarketingBlogIndexRoute
  PublicmarketingDesignSystemIndexRoute: typeof PublicmarketingDesignSystemIndexRoute
  PublicmarketingBlogCategorySlugRoute: typeof PublicmarketingBlogCategorySlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PubliclegalPrivacyRoute: PubliclegalPrivacyRoute,
  PubliclegalTermsRoute: PubliclegalTermsRoute,
  PublicmarketingContactRoute: PublicmarketingContactRoute,
  PublicmarketingBlogSlugRoute: PublicmarketingBlogSlugRoute,
  PublicmarketinglandingPageIndexRoute: PublicmarketinglandingPageIndexRoute,
  PublicmarketingBlogIndexRoute: PublicmarketingBlogIndexRoute,
  PublicmarketingDesignSystemIndexRoute: PublicmarketingDesignSystemIndexRoute,
  PublicmarketingBlogCategorySlugRoute: PublicmarketingBlogCategorySlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface BillingRouteRouteChildren {
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

const BillingRouteRouteChildren: BillingRouteRouteChildren = {
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}

const BillingRouteRouteWithChildren = BillingRouteRoute._addFileChildren(
  BillingRouteRouteChildren,
)

interface LibraryRouteChildren {
  LibraryGenreSlugRoute: typeof LibraryGenreSlugRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryGenreSlugRoute: LibraryGenreSlugRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface authAuthUnauthedRouteRouteChildren {
  authAuthUnauthedForgotPasswordRoute: typeof authAuthUnauthedForgotPasswordRoute
  authAuthUnauthedSignInRoute: typeof authAuthUnauthedSignInRoute
  authAuthUnauthedSignUpRoute: typeof authAuthUnauthedSignUpRoute
}

const authAuthUnauthedRouteRouteChildren: authAuthUnauthedRouteRouteChildren = {
  authAuthUnauthedForgotPasswordRoute: authAuthUnauthedForgotPasswordRoute,
  authAuthUnauthedSignInRoute: authAuthUnauthedSignInRoute,
  authAuthUnauthedSignUpRoute: authAuthUnauthedSignUpRoute,
}

const authAuthUnauthedRouteRouteWithChildren =
  authAuthUnauthedRouteRoute._addFileChildren(
    authAuthUnauthedRouteRouteChildren,
  )

interface authAuthRouteRouteChildren {
  authAuthUnauthedRouteRoute: typeof authAuthUnauthedRouteRouteWithChildren
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthUnauthedRouteRoute: authAuthUnauthedRouteRouteWithChildren,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

interface AutheddashboardAdminRouteChildren {
  AutheddashboardAdminAnalyticsRoute: typeof AutheddashboardAdminAnalyticsRoute
  AutheddashboardAdminAuditRoute: typeof AutheddashboardAdminAuditRoute
  AutheddashboardAdminIntegrationsRoute: typeof AutheddashboardAdminIntegrationsRoute
  AutheddashboardAdminPaymentsRoute: typeof AutheddashboardAdminPaymentsRoute
  AutheddashboardAdminSystemRoute: typeof AutheddashboardAdminSystemRoute
  AutheddashboardAdminUsersRoute: typeof AutheddashboardAdminUsersRoute
  AutheddashboardAdminIndexRoute: typeof AutheddashboardAdminIndexRoute
  AutheddashboardAdminSupportTicketIdRoute: typeof AutheddashboardAdminSupportTicketIdRoute
  AutheddashboardAdminSupportIndexRoute: typeof AutheddashboardAdminSupportIndexRoute
}

const AutheddashboardAdminRouteChildren: AutheddashboardAdminRouteChildren = {
  AutheddashboardAdminAnalyticsRoute: AutheddashboardAdminAnalyticsRoute,
  AutheddashboardAdminAuditRoute: AutheddashboardAdminAuditRoute,
  AutheddashboardAdminIntegrationsRoute: AutheddashboardAdminIntegrationsRoute,
  AutheddashboardAdminPaymentsRoute: AutheddashboardAdminPaymentsRoute,
  AutheddashboardAdminSystemRoute: AutheddashboardAdminSystemRoute,
  AutheddashboardAdminUsersRoute: AutheddashboardAdminUsersRoute,
  AutheddashboardAdminIndexRoute: AutheddashboardAdminIndexRoute,
  AutheddashboardAdminSupportTicketIdRoute:
    AutheddashboardAdminSupportTicketIdRoute,
  AutheddashboardAdminSupportIndexRoute: AutheddashboardAdminSupportIndexRoute,
}

const AutheddashboardAdminRouteWithChildren =
  AutheddashboardAdminRoute._addFileChildren(AutheddashboardAdminRouteChildren)

interface AutheddashboardRouteRouteChildren {
  AutheddashboardDashboardRouteRoute: typeof AutheddashboardDashboardRouteRoute
  AutheddashboardAdminRoute: typeof AutheddashboardAdminRouteWithChildren
  AutheddashboardHelpRoute: typeof AutheddashboardHelpRoute
  AutheddashboardPurchasesRoute: typeof AutheddashboardPurchasesRoute
  AutheddashboardCreditsPurchaseRoute: typeof AutheddashboardCreditsPurchaseRoute
  AutheddashboardCreditsTransactionsRoute: typeof AutheddashboardCreditsTransactionsRoute
  AutheddashboardSettingsBillingRoute: typeof AutheddashboardSettingsBillingRoute
  AutheddashboardSettingsProfileRoute: typeof AutheddashboardSettingsProfileRoute
  AutheddashboardSettingsSecurityRoute: typeof AutheddashboardSettingsSecurityRoute
  AutheddashboardTicketsTicketIdRoute: typeof AutheddashboardTicketsTicketIdRoute
  AutheddashboardSettingsIndexRoute: typeof AutheddashboardSettingsIndexRoute
  AutheddashboardTicketsIndexRoute: typeof AutheddashboardTicketsIndexRoute
}

const AutheddashboardRouteRouteChildren: AutheddashboardRouteRouteChildren = {
  AutheddashboardDashboardRouteRoute: AutheddashboardDashboardRouteRoute,
  AutheddashboardAdminRoute: AutheddashboardAdminRouteWithChildren,
  AutheddashboardHelpRoute: AutheddashboardHelpRoute,
  AutheddashboardPurchasesRoute: AutheddashboardPurchasesRoute,
  AutheddashboardCreditsPurchaseRoute: AutheddashboardCreditsPurchaseRoute,
  AutheddashboardCreditsTransactionsRoute:
    AutheddashboardCreditsTransactionsRoute,
  AutheddashboardSettingsBillingRoute: AutheddashboardSettingsBillingRoute,
  AutheddashboardSettingsProfileRoute: AutheddashboardSettingsProfileRoute,
  AutheddashboardSettingsSecurityRoute: AutheddashboardSettingsSecurityRoute,
  AutheddashboardTicketsTicketIdRoute: AutheddashboardTicketsTicketIdRoute,
  AutheddashboardSettingsIndexRoute: AutheddashboardSettingsIndexRoute,
  AutheddashboardTicketsIndexRoute: AutheddashboardTicketsIndexRoute,
}

const AutheddashboardRouteRouteWithChildren =
  AutheddashboardRouteRoute._addFileChildren(AutheddashboardRouteRouteChildren)

interface NovelSlugRouteChildren {
  NovelSlugChapterNumberRoute: typeof NovelSlugChapterNumberRoute
}

const NovelSlugRouteChildren: NovelSlugRouteChildren = {
  NovelSlugChapterNumberRoute: NovelSlugChapterNumberRoute,
}

const NovelSlugRouteWithChildren = NovelSlugRoute._addFileChildren(
  NovelSlugRouteChildren,
)

interface NovelsSlugRouteChildren {
  NovelsSlugChapterNumberRoute: typeof NovelsSlugChapterNumberRoute
}

const NovelsSlugRouteChildren: NovelsSlugRouteChildren = {
  NovelsSlugChapterNumberRoute: NovelsSlugChapterNumberRoute,
}

const NovelsSlugRouteWithChildren = NovelsSlugRoute._addFileChildren(
  NovelsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  BillingRouteRoute: BillingRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  PageRoute: PageRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  LibraryRoute: LibraryRouteWithChildren,
  RankingRoute: RankingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
  AutheddashboardRouteRoute: AutheddashboardRouteRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiSearchRoute: ApiSearchRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  ForumsThreadIdRoute: ForumsThreadIdRoute,
  NovelSlugRoute: NovelSlugRouteWithChildren,
  NovelsSlugRoute: NovelsSlugRouteWithChildren,
  TagsSlugRoute: TagsSlugRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  NovelsIndexRoute: NovelsIndexRoute,
  WorldsIndexRoute: WorldsIndexRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
  NovelsCategoriesSlugRoute: NovelsCategoriesSlugRoute,
  NovelsGenreSlugRoute: NovelsGenreSlugRoute,
  TagsNovelsSlugRoute: TagsNovelsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
