/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BillingRouteRouteImport } from './routes/billing/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AutheddashboardRouteRouteImport } from './routes/_authed/(dashboard)/route'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/auth/route'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as PublicmarketingContactRouteImport } from './routes/_public/(marketing)/contact'
import { Route as PubliclegalTermsRouteImport } from './routes/_public/(legal)/terms'
import { Route as PubliclegalPrivacyRouteImport } from './routes/_public/(legal)/privacy'
import { Route as AutheddashboardAdminRouteImport } from './routes/_authed/(dashboard)/admin'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/auth/reset-password'
import { Route as AutheddashboardDashboardRouteRouteImport } from './routes/_authed/(dashboard)/dashboard/route'
import { Route as authAuthUnauthedRouteRouteImport } from './routes/(auth)/auth/_unauthed/route'
import { Route as PublicmarketingBlogIndexRouteImport } from './routes/_public/(marketing)/blog/index'
import { Route as PublicmarketinglandingPageIndexRouteImport } from './routes/_public/(marketing)/(landing-page)/index'
import { Route as AutheddashboardSettingsIndexRouteImport } from './routes/_authed/(dashboard)/settings/index'
import { Route as PublicmarketingTemplatesListingRouteImport } from './routes/_public/(marketing)/templates/listing'
import { Route as PublicmarketingTemplatesLandingComposerRouteImport } from './routes/_public/(marketing)/templates/landing-composer'
import { Route as PublicmarketingTemplatesSlugRouteImport } from './routes/_public/(marketing)/templates/$slug'
import { Route as PublicmarketingBlogSlugRouteImport } from './routes/_public/(marketing)/blog/$slug'
import { Route as AutheddashboardSettingsSecurityRouteImport } from './routes/_authed/(dashboard)/settings/security'
import { Route as AutheddashboardSettingsProfileRouteImport } from './routes/_authed/(dashboard)/settings/profile'
import { Route as AutheddashboardSettingsBillingRouteImport } from './routes/_authed/(dashboard)/settings/billing'
import { Route as AutheddashboardCreditsTransactionsRouteImport } from './routes/_authed/(dashboard)/credits/transactions'
import { Route as AutheddashboardCreditsPurchaseRouteImport } from './routes/_authed/(dashboard)/credits/purchase'
import { Route as authAuthUnauthedSignUpRouteImport } from './routes/(auth)/auth/_unauthed/sign-up'
import { Route as authAuthUnauthedSignInRouteImport } from './routes/(auth)/auth/_unauthed/sign-in'
import { Route as authAuthUnauthedPhoneVerifyRouteImport } from './routes/(auth)/auth/_unauthed/phone-verify'
import { Route as authAuthUnauthedForgotPasswordRouteImport } from './routes/(auth)/auth/_unauthed/forgot-password'
import { Route as PublicmarketingBlogCategorySlugRouteImport } from './routes/_public/(marketing)/blog/category/$slug'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRouteRoute = BillingRouteRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRouteRoute,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => BillingRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AutheddashboardRouteRoute = AutheddashboardRouteRouteImport.update({
  id: '/_authed/(dashboard)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicmarketingContactRoute = PublicmarketingContactRouteImport.update({
  id: '/(marketing)/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PubliclegalTermsRoute = PubliclegalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PubliclegalPrivacyRoute = PubliclegalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AutheddashboardAdminRoute = AutheddashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AutheddashboardRouteRoute,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const AutheddashboardDashboardRouteRoute =
  AutheddashboardDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const authAuthUnauthedRouteRoute = authAuthUnauthedRouteRouteImport.update({
  id: '/_unauthed',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const PublicmarketingBlogIndexRoute =
  PublicmarketingBlogIndexRouteImport.update({
    id: '/(marketing)/blog/',
    path: '/blog/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicmarketinglandingPageIndexRoute =
  PublicmarketinglandingPageIndexRouteImport.update({
    id: '/(marketing)/(landing-page)/',
    path: '/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AutheddashboardSettingsIndexRoute =
  AutheddashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const PublicmarketingTemplatesListingRoute =
  PublicmarketingTemplatesListingRouteImport.update({
    id: '/(marketing)/templates/listing',
    path: '/templates/listing',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicmarketingTemplatesLandingComposerRoute =
  PublicmarketingTemplatesLandingComposerRouteImport.update({
    id: '/(marketing)/templates/landing-composer',
    path: '/templates/landing-composer',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicmarketingTemplatesSlugRoute =
  PublicmarketingTemplatesSlugRouteImport.update({
    id: '/(marketing)/templates/$slug',
    path: '/templates/$slug',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicmarketingBlogSlugRoute = PublicmarketingBlogSlugRouteImport.update({
  id: '/(marketing)/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AutheddashboardSettingsSecurityRoute =
  AutheddashboardSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardSettingsProfileRoute =
  AutheddashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardSettingsBillingRoute =
  AutheddashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardCreditsTransactionsRoute =
  AutheddashboardCreditsTransactionsRouteImport.update({
    id: '/credits/transactions',
    path: '/credits/transactions',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const AutheddashboardCreditsPurchaseRoute =
  AutheddashboardCreditsPurchaseRouteImport.update({
    id: '/credits/purchase',
    path: '/credits/purchase',
    getParentRoute: () => AutheddashboardRouteRoute,
  } as any)
const authAuthUnauthedSignUpRoute = authAuthUnauthedSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthUnauthedRouteRoute,
} as any)
const authAuthUnauthedSignInRoute = authAuthUnauthedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthUnauthedRouteRoute,
} as any)
const authAuthUnauthedPhoneVerifyRoute =
  authAuthUnauthedPhoneVerifyRouteImport.update({
    id: '/phone-verify',
    path: '/phone-verify',
    getParentRoute: () => authAuthUnauthedRouteRoute,
  } as any)
const authAuthUnauthedForgotPasswordRoute =
  authAuthUnauthedForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authAuthUnauthedRouteRoute,
  } as any)
const PublicmarketingBlogCategorySlugRoute =
  PublicmarketingBlogCategorySlugRouteImport.update({
    id: '/(marketing)/blog/category/$slug',
    path: '/blog/category/$slug',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicmarketinglandingPageIndexRoute
  '/billing': typeof BillingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof authAuthUnauthedRouteRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/search': typeof ApiSearchRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/docs/$': typeof DocsSplatRoute
  '/dashboard': typeof AutheddashboardDashboardRouteRoute
  '/auth/reset-password': typeof authAuthResetPasswordRoute
  '/admin': typeof AutheddashboardAdminRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/terms': typeof PubliclegalTermsRoute
  '/contact': typeof PublicmarketingContactRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/auth/forgot-password': typeof authAuthUnauthedForgotPasswordRoute
  '/auth/phone-verify': typeof authAuthUnauthedPhoneVerifyRoute
  '/auth/sign-in': typeof authAuthUnauthedSignInRoute
  '/auth/sign-up': typeof authAuthUnauthedSignUpRoute
  '/credits/purchase': typeof AutheddashboardCreditsPurchaseRoute
  '/credits/transactions': typeof AutheddashboardCreditsTransactionsRoute
  '/settings/billing': typeof AutheddashboardSettingsBillingRoute
  '/settings/profile': typeof AutheddashboardSettingsProfileRoute
  '/settings/security': typeof AutheddashboardSettingsSecurityRoute
  '/blog/$slug': typeof PublicmarketingBlogSlugRoute
  '/templates/$slug': typeof PublicmarketingTemplatesSlugRoute
  '/templates/landing-composer': typeof PublicmarketingTemplatesLandingComposerRoute
  '/templates/listing': typeof PublicmarketingTemplatesListingRoute
  '/settings/': typeof AutheddashboardSettingsIndexRoute
  '/blog/': typeof PublicmarketingBlogIndexRoute
  '/blog/category/$slug': typeof PublicmarketingBlogCategorySlugRoute
}
export interface FileRoutesByTo {
  '/billing': typeof BillingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof authAuthUnauthedRouteRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/search': typeof ApiSearchRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/docs/$': typeof DocsSplatRoute
  '/dashboard': typeof AutheddashboardDashboardRouteRoute
  '/auth/reset-password': typeof authAuthResetPasswordRoute
  '/admin': typeof AutheddashboardAdminRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/terms': typeof PubliclegalTermsRoute
  '/contact': typeof PublicmarketingContactRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/auth/forgot-password': typeof authAuthUnauthedForgotPasswordRoute
  '/auth/phone-verify': typeof authAuthUnauthedPhoneVerifyRoute
  '/auth/sign-in': typeof authAuthUnauthedSignInRoute
  '/auth/sign-up': typeof authAuthUnauthedSignUpRoute
  '/credits/purchase': typeof AutheddashboardCreditsPurchaseRoute
  '/credits/transactions': typeof AutheddashboardCreditsTransactionsRoute
  '/settings/billing': typeof AutheddashboardSettingsBillingRoute
  '/settings/profile': typeof AutheddashboardSettingsProfileRoute
  '/settings/security': typeof AutheddashboardSettingsSecurityRoute
  '/blog/$slug': typeof PublicmarketingBlogSlugRoute
  '/templates/$slug': typeof PublicmarketingTemplatesSlugRoute
  '/templates/landing-composer': typeof PublicmarketingTemplatesLandingComposerRoute
  '/templates/listing': typeof PublicmarketingTemplatesListingRoute
  '/settings': typeof AutheddashboardSettingsIndexRoute
  '/': typeof PublicmarketinglandingPageIndexRoute
  '/blog': typeof PublicmarketingBlogIndexRoute
  '/blog/category/$slug': typeof PublicmarketingBlogCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/billing': typeof BillingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(auth)/auth': typeof authAuthRouteRouteWithChildren
  '/_authed/(dashboard)': typeof AutheddashboardRouteRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/search': typeof ApiSearchRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/docs/$': typeof DocsSplatRoute
  '/(auth)/auth/_unauthed': typeof authAuthUnauthedRouteRouteWithChildren
  '/_authed/(dashboard)/dashboard': typeof AutheddashboardDashboardRouteRoute
  '/(auth)/auth/reset-password': typeof authAuthResetPasswordRoute
  '/_authed/(dashboard)/admin': typeof AutheddashboardAdminRoute
  '/_public/(legal)/privacy': typeof PubliclegalPrivacyRoute
  '/_public/(legal)/terms': typeof PubliclegalTermsRoute
  '/_public/(marketing)/contact': typeof PublicmarketingContactRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/(auth)/auth/_unauthed/forgot-password': typeof authAuthUnauthedForgotPasswordRoute
  '/(auth)/auth/_unauthed/phone-verify': typeof authAuthUnauthedPhoneVerifyRoute
  '/(auth)/auth/_unauthed/sign-in': typeof authAuthUnauthedSignInRoute
  '/(auth)/auth/_unauthed/sign-up': typeof authAuthUnauthedSignUpRoute
  '/_authed/(dashboard)/credits/purchase': typeof AutheddashboardCreditsPurchaseRoute
  '/_authed/(dashboard)/credits/transactions': typeof AutheddashboardCreditsTransactionsRoute
  '/_authed/(dashboard)/settings/billing': typeof AutheddashboardSettingsBillingRoute
  '/_authed/(dashboard)/settings/profile': typeof AutheddashboardSettingsProfileRoute
  '/_authed/(dashboard)/settings/security': typeof AutheddashboardSettingsSecurityRoute
  '/_public/(marketing)/blog/$slug': typeof PublicmarketingBlogSlugRoute
  '/_public/(marketing)/templates/$slug': typeof PublicmarketingTemplatesSlugRoute
  '/_public/(marketing)/templates/landing-composer': typeof PublicmarketingTemplatesLandingComposerRoute
  '/_public/(marketing)/templates/listing': typeof PublicmarketingTemplatesListingRoute
  '/_authed/(dashboard)/settings/': typeof AutheddashboardSettingsIndexRoute
  '/_public/(marketing)/(landing-page)/': typeof PublicmarketinglandingPageIndexRoute
  '/_public/(marketing)/blog/': typeof PublicmarketingBlogIndexRoute
  '/_public/(marketing)/blog/category/$slug': typeof PublicmarketingBlogCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/$'
    | '/auth'
    | '/api/contact'
    | '/api/search'
    | '/billing/cancel'
    | '/billing/success'
    | '/docs/$'
    | '/dashboard'
    | '/auth/reset-password'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/api/newsletter/subscribe'
    | '/auth/forgot-password'
    | '/auth/phone-verify'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/credits/purchase'
    | '/credits/transactions'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/blog/$slug'
    | '/templates/$slug'
    | '/templates/landing-composer'
    | '/templates/listing'
    | '/settings/'
    | '/blog/'
    | '/blog/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billing'
    | '/$'
    | '/auth'
    | '/api/contact'
    | '/api/search'
    | '/billing/cancel'
    | '/billing/success'
    | '/docs/$'
    | '/dashboard'
    | '/auth/reset-password'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/api/newsletter/subscribe'
    | '/auth/forgot-password'
    | '/auth/phone-verify'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/credits/purchase'
    | '/credits/transactions'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/blog/$slug'
    | '/templates/$slug'
    | '/templates/landing-composer'
    | '/templates/listing'
    | '/settings'
    | '/'
    | '/blog'
    | '/blog/category/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/billing'
    | '/$'
    | '/(auth)/auth'
    | '/_authed/(dashboard)'
    | '/api/contact'
    | '/api/search'
    | '/billing/cancel'
    | '/billing/success'
    | '/docs/$'
    | '/(auth)/auth/_unauthed'
    | '/_authed/(dashboard)/dashboard'
    | '/(auth)/auth/reset-password'
    | '/_authed/(dashboard)/admin'
    | '/_public/(legal)/privacy'
    | '/_public/(legal)/terms'
    | '/_public/(marketing)/contact'
    | '/api/newsletter/subscribe'
    | '/(auth)/auth/_unauthed/forgot-password'
    | '/(auth)/auth/_unauthed/phone-verify'
    | '/(auth)/auth/_unauthed/sign-in'
    | '/(auth)/auth/_unauthed/sign-up'
    | '/_authed/(dashboard)/credits/purchase'
    | '/_authed/(dashboard)/credits/transactions'
    | '/_authed/(dashboard)/settings/billing'
    | '/_authed/(dashboard)/settings/profile'
    | '/_authed/(dashboard)/settings/security'
    | '/_public/(marketing)/blog/$slug'
    | '/_public/(marketing)/templates/$slug'
    | '/_public/(marketing)/templates/landing-composer'
    | '/_public/(marketing)/templates/listing'
    | '/_authed/(dashboard)/settings/'
    | '/_public/(marketing)/(landing-page)/'
    | '/_public/(marketing)/blog/'
    | '/_public/(marketing)/blog/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  BillingRouteRoute: typeof BillingRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
  AutheddashboardRouteRoute: typeof AutheddashboardRouteRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof BillingRouteRoute
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof BillingRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/(dashboard)': {
      id: '/_authed/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AutheddashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/(marketing)/contact': {
      id: '/_public/(marketing)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicmarketingContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(legal)/terms': {
      id: '/_public/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PubliclegalTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(legal)/privacy': {
      id: '/_public/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PubliclegalPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/(dashboard)/admin': {
      id: '/_authed/(dashboard)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AutheddashboardAdminRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/(auth)/auth/reset-password': {
      id: '/(auth)/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/_authed/(dashboard)/dashboard': {
      id: '/_authed/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AutheddashboardDashboardRouteRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/(auth)/auth/_unauthed': {
      id: '/(auth)/auth/_unauthed'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthUnauthedRouteRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/_public/(marketing)/blog/': {
      id: '/_public/(marketing)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicmarketingBlogIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/(landing-page)/': {
      id: '/_public/(marketing)/(landing-page)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicmarketinglandingPageIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/(dashboard)/settings/': {
      id: '/_authed/(dashboard)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AutheddashboardSettingsIndexRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_public/(marketing)/templates/listing': {
      id: '/_public/(marketing)/templates/listing'
      path: '/templates/listing'
      fullPath: '/templates/listing'
      preLoaderRoute: typeof PublicmarketingTemplatesListingRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/templates/landing-composer': {
      id: '/_public/(marketing)/templates/landing-composer'
      path: '/templates/landing-composer'
      fullPath: '/templates/landing-composer'
      preLoaderRoute: typeof PublicmarketingTemplatesLandingComposerRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/templates/$slug': {
      id: '/_public/(marketing)/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof PublicmarketingTemplatesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(marketing)/blog/$slug': {
      id: '/_public/(marketing)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicmarketingBlogSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/(dashboard)/settings/security': {
      id: '/_authed/(dashboard)/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AutheddashboardSettingsSecurityRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/settings/profile': {
      id: '/_authed/(dashboard)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AutheddashboardSettingsProfileRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/settings/billing': {
      id: '/_authed/(dashboard)/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AutheddashboardSettingsBillingRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/credits/transactions': {
      id: '/_authed/(dashboard)/credits/transactions'
      path: '/credits/transactions'
      fullPath: '/credits/transactions'
      preLoaderRoute: typeof AutheddashboardCreditsTransactionsRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/_authed/(dashboard)/credits/purchase': {
      id: '/_authed/(dashboard)/credits/purchase'
      path: '/credits/purchase'
      fullPath: '/credits/purchase'
      preLoaderRoute: typeof AutheddashboardCreditsPurchaseRouteImport
      parentRoute: typeof AutheddashboardRouteRoute
    }
    '/(auth)/auth/_unauthed/sign-up': {
      id: '/(auth)/auth/_unauthed/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof authAuthUnauthedSignUpRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/(auth)/auth/_unauthed/sign-in': {
      id: '/(auth)/auth/_unauthed/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof authAuthUnauthedSignInRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/(auth)/auth/_unauthed/phone-verify': {
      id: '/(auth)/auth/_unauthed/phone-verify'
      path: '/phone-verify'
      fullPath: '/auth/phone-verify'
      preLoaderRoute: typeof authAuthUnauthedPhoneVerifyRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/(auth)/auth/_unauthed/forgot-password': {
      id: '/(auth)/auth/_unauthed/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authAuthUnauthedForgotPasswordRouteImport
      parentRoute: typeof authAuthUnauthedRouteRoute
    }
    '/_public/(marketing)/blog/category/$slug': {
      id: '/_public/(marketing)/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof PublicmarketingBlogCategorySlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PubliclegalPrivacyRoute: typeof PubliclegalPrivacyRoute
  PubliclegalTermsRoute: typeof PubliclegalTermsRoute
  PublicmarketingContactRoute: typeof PublicmarketingContactRoute
  PublicmarketingBlogSlugRoute: typeof PublicmarketingBlogSlugRoute
  PublicmarketingTemplatesSlugRoute: typeof PublicmarketingTemplatesSlugRoute
  PublicmarketingTemplatesLandingComposerRoute: typeof PublicmarketingTemplatesLandingComposerRoute
  PublicmarketingTemplatesListingRoute: typeof PublicmarketingTemplatesListingRoute
  PublicmarketinglandingPageIndexRoute: typeof PublicmarketinglandingPageIndexRoute
  PublicmarketingBlogIndexRoute: typeof PublicmarketingBlogIndexRoute
  PublicmarketingBlogCategorySlugRoute: typeof PublicmarketingBlogCategorySlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PubliclegalPrivacyRoute: PubliclegalPrivacyRoute,
  PubliclegalTermsRoute: PubliclegalTermsRoute,
  PublicmarketingContactRoute: PublicmarketingContactRoute,
  PublicmarketingBlogSlugRoute: PublicmarketingBlogSlugRoute,
  PublicmarketingTemplatesSlugRoute: PublicmarketingTemplatesSlugRoute,
  PublicmarketingTemplatesLandingComposerRoute:
    PublicmarketingTemplatesLandingComposerRoute,
  PublicmarketingTemplatesListingRoute: PublicmarketingTemplatesListingRoute,
  PublicmarketinglandingPageIndexRoute: PublicmarketinglandingPageIndexRoute,
  PublicmarketingBlogIndexRoute: PublicmarketingBlogIndexRoute,
  PublicmarketingBlogCategorySlugRoute: PublicmarketingBlogCategorySlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface BillingRouteRouteChildren {
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

const BillingRouteRouteChildren: BillingRouteRouteChildren = {
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}

const BillingRouteRouteWithChildren = BillingRouteRoute._addFileChildren(
  BillingRouteRouteChildren,
)

interface authAuthUnauthedRouteRouteChildren {
  authAuthUnauthedForgotPasswordRoute: typeof authAuthUnauthedForgotPasswordRoute
  authAuthUnauthedPhoneVerifyRoute: typeof authAuthUnauthedPhoneVerifyRoute
  authAuthUnauthedSignInRoute: typeof authAuthUnauthedSignInRoute
  authAuthUnauthedSignUpRoute: typeof authAuthUnauthedSignUpRoute
}

const authAuthUnauthedRouteRouteChildren: authAuthUnauthedRouteRouteChildren = {
  authAuthUnauthedForgotPasswordRoute: authAuthUnauthedForgotPasswordRoute,
  authAuthUnauthedPhoneVerifyRoute: authAuthUnauthedPhoneVerifyRoute,
  authAuthUnauthedSignInRoute: authAuthUnauthedSignInRoute,
  authAuthUnauthedSignUpRoute: authAuthUnauthedSignUpRoute,
}

const authAuthUnauthedRouteRouteWithChildren =
  authAuthUnauthedRouteRoute._addFileChildren(
    authAuthUnauthedRouteRouteChildren,
  )

interface authAuthRouteRouteChildren {
  authAuthUnauthedRouteRoute: typeof authAuthUnauthedRouteRouteWithChildren
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthUnauthedRouteRoute: authAuthUnauthedRouteRouteWithChildren,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

interface AutheddashboardRouteRouteChildren {
  AutheddashboardDashboardRouteRoute: typeof AutheddashboardDashboardRouteRoute
  AutheddashboardAdminRoute: typeof AutheddashboardAdminRoute
  AutheddashboardCreditsPurchaseRoute: typeof AutheddashboardCreditsPurchaseRoute
  AutheddashboardCreditsTransactionsRoute: typeof AutheddashboardCreditsTransactionsRoute
  AutheddashboardSettingsBillingRoute: typeof AutheddashboardSettingsBillingRoute
  AutheddashboardSettingsProfileRoute: typeof AutheddashboardSettingsProfileRoute
  AutheddashboardSettingsSecurityRoute: typeof AutheddashboardSettingsSecurityRoute
  AutheddashboardSettingsIndexRoute: typeof AutheddashboardSettingsIndexRoute
}

const AutheddashboardRouteRouteChildren: AutheddashboardRouteRouteChildren = {
  AutheddashboardDashboardRouteRoute: AutheddashboardDashboardRouteRoute,
  AutheddashboardAdminRoute: AutheddashboardAdminRoute,
  AutheddashboardCreditsPurchaseRoute: AutheddashboardCreditsPurchaseRoute,
  AutheddashboardCreditsTransactionsRoute:
    AutheddashboardCreditsTransactionsRoute,
  AutheddashboardSettingsBillingRoute: AutheddashboardSettingsBillingRoute,
  AutheddashboardSettingsProfileRoute: AutheddashboardSettingsProfileRoute,
  AutheddashboardSettingsSecurityRoute: AutheddashboardSettingsSecurityRoute,
  AutheddashboardSettingsIndexRoute: AutheddashboardSettingsIndexRoute,
}

const AutheddashboardRouteRouteWithChildren =
  AutheddashboardRouteRoute._addFileChildren(AutheddashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  BillingRouteRoute: BillingRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
  AutheddashboardRouteRoute: AutheddashboardRouteRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
